### ISSUE TITLE
tailwind.css file is not being updated in Rails 8 with tailwindcss-ruby 4.0.0.alpha27

### ISSUE THREAD

**Issue by pinzonjulian** [rails/tailwindcss-rails#419] opened 2024-10-17 12:27 UTC
Whenever I update the `app/assets/stylesheets/application.tailwind.css` file, the corresponding output file at `app/assets/builds/tailwind.css` does not update.

The process seems to be doing something:

<img width="1106" alt="image" src="https://github.com/user-attachments/assets/f551c402-9f5b-4c29-8620-26be77eb6f59">

But the changes are not being picked up. Notice the execution time on the watcher vs the updated timestamps on the file:

<img width="781" alt="Screenshot 2024-10-17 at 11 21 24 PM" src="https://github.com/user-attachments/assets/38e872d2-d84b-4e14-8083-238843a27644">

The only way to get this to work is to delete the file, stop the watcher (i.e. `bin/dev` in a rails app) and run the watcher again.

I created an app to try out the new setup and experiment on Tailwind v4. The only notable thing about it is that I removed the `tailwind.config.js` file since it's not supposed to be needed in Tailwind v4. I tried adding it back and that did not resolve the issue.

https://github.com/pinzonjulian/tw4-experiments

**Gem versions**
tailwindcss-rails (3.0.0)
tailwindcss-ruby (4.0.0.alpha.27)
rails (8.0.0.beta1)

Running on macOS Sonoma 14.6.1

**Comment by flavorjones** [comment] 2024-10-17 14:20
Thanks for opening this issue. I haven't tried using the new alpha releases yet, but I'll take a look as soon as I can.

**Comment by flavorjones** [comment] 2024-10-17 14:36
Ah! Tailwindcss 4 is trying to be much smarter about detecting files, but it looks like if the `-i` argument is given then it ignores any other files.

Should be a pretty easy thing to fix ... I will create a draft branch and maybe you can try it out and let me know if it works.

**Comment by flavorjones** [comment] 2024-10-17 15:36
@pinzonjulian Can you try out the branch from https://github.com/rails/tailwindcss-rails/pull/420 and let me know what you think?

**Comment by flavorjones** [comment] 2024-10-18 01:53
Responding to your comments on #420 ...

> I believe it's even introduced some regressions

I'm not sure how anything can regress from "file doesn't get generated" 🤣, but I understand that it's not working for your use case.

In #420 I removed the `-i app/assets/stylesheets/application.tailwind.css` because it seemed like its presence was preventing the CLI from generating the output file ... I'll double check and if that's the case I can report a bug upstream.

I added some tests in #420 that ensure CSS is generated appropriately for scaffolds (in the user journey test). Can you suggest an assertion we can add there that would be meaningful for your use case?

Are you able to figure out a command line (not relying on this gem) that would accomplish what you want with the v4 alpha CLI? (You can run `bin/rails tailwindcss:build[verbose]` to see what the command being run by this gem.)

**Comment by flavorjones** [comment] 2024-10-18 02:25
OK, I'm digging back into your report and ... I misunderstood, and my local testing was still using v3 syntax in the `application.tailwind.css` file. Sorry for the confusion.

It sounds like you're saying that the CSS was being generated correctly, but that "watch" isn't updating? I've confirmed that I see that behavior locally, too. Can I ask you to report this upstream? You can use the `bin/rails tailwindcss:build[verbose]` to describe what the command is that's being run.

In the meantime, I'll revert the change that broke handling of `application.tailwind.css`, give me a few minutes.

**Comment by flavorjones** [comment] 2024-10-18 02:34
See https://github.com/rails/tailwindcss-rails/pull/423

**Comment by flavorjones** [comment] 2024-10-18 02:39
> It sounds like you're saying that the CSS was being generated correctly, but that "watch" isn't updating? 

Interestingly, if I put something like this in my `application.tailwind.css`:

```css
@import "tailwindcss";
body {
   background: #00aa00;
}
```

and I change the background color, then everything works fine for me when I `watch`. So if you're seeing something different with `@theme` and/or variables, then I'm guessing it's a bug upstream.

**Comment by flavorjones** [comment] 2024-10-18 13:06
@pinzonjulian I've merged #423 which should fix the regression from #420. At this point, I think the issue you're describing is from the upstream `tailwindcss` executable ... does that sound like a correct diagnosis? If not, what am I missing?

**Comment by pinzonjulian** [comment] 2024-10-18 21:35
Thanks for that @flavorjones ! 

I've tested the reverted changes and it's working back to where it was. I do agree that there's something going on with the `watch` command. I tried updating the css file with the `@theme` directive in `watch` mode and it doesn't work. However if I try to manually run the `build` command it does update the output stylesheet. I'll do some more testing and let you know if I find anything and if I end up creating an issue upstream. 

What do you think about adding a test for the watch command in the integration test as well?

**Comment by pinzonjulian** [comment] 2024-10-18 22:10
You were spot on with your assessment @flavorjones. I tried the standalone CLI without Rails and indeed the `--watch` feature is not working on their end.  I've [created an issue](https://github.com/tailwindlabs/tailwindcss/issues/14726) in Tailwind.

**Comment by flavorjones** [comment] 2024-10-20 18:34
> What do you think about adding a test for the watch command in the integration test as well?

We haven't needed to until now; and I'm not sure adding complexity to the user journey test would be worth the effort. If you want to give it a try and can make it work reliably, I'd be happy to merge it, though!

I don't think there's anything else this project can do at this point, so I'm going to close this issue. But I'm happy to continue the conversation.

**Closed by flavorjones** 2024-10-20 18:34 UTC
