### ISSUE TITLE
Running `rails assets:clean assets:precompile` produces no public/assets/tailwind-[hash].css 

### ISSUE THREAD

**Issue by grncdr** [rails/tailwindcss-rails#379] opened 2024-07-11 06:42 UTC
This is in a Rails 7 project using Propshaft.

Our CI was set up to run `rails assets:clean assets:precompile` (as a single command) due to some older asset caching. However, if you run this in a fresh checkout (e.g. before `app/assets/tailwind.css` has been generated) there will be no tailwind.css in the resulting `public/assets/.manifest.json` nor `public/assets/tailwind-[hash].css` file.

Running `rails assets:precompile` alone does not exhibit this behaviour.

**Comment by flavorjones** [comment] 2024-07-11 19:41
@grncdr Sorry you're having problems. I'll try to help.

I can't reproduce this with a fresh Rails 7.1.3.4 app created with

```
rails new foo -a propshaft -c tailwind
```

Is it possible for you to help me reproduce this so I can diagnose what's going on? Can you create a github repo that reproduces, or give me more information about your application?

**Comment by grncdr** [comment] 2024-07-14 01:33
Sorry for the brief report, it was late and I was just happy to have working CI again.

I will see if I can find some time to create a reproduction but I'm traveling at the moment.

**Comment by flavorjones** [comment] 2024-07-14 19:58
@grncdr OK, I'm going to close this for now, but will reopen if you can help me reproduce this! Thank you!

**Closed by flavorjones** 2024-07-14 19:58 UTC
Labels: question

**Comment by sebastialonso** [comment] 2024-12-03 01:05
@flavorjones I'm experiencing the same when deploying in production environment. I've uploaded [this almost bare-bones repo](https://github.com/sebastialonso/tailwindcss-rails-dokku) for reproduction. I'm deploying wiht Dokku.

Was created through `rails new blog-dokku --css tailwind --database=postgresql`.
After deployment, requesting a view fails in the logs with

```
2024-12-03T00:53:18.360190000Z app[web.1]: [ea8e8776-571f-42bc-b8bc-d9699219293d] Sprockets::Rails::Helper::AssetNotFound (The asset "tailwind.css" is not present in the asset pipeline.
2024-12-03T00:53:18.360202143Z app[web.1]: )
2024-12-03T00:53:18.360204540Z app[web.1]: [ea8e8776-571f-42bc-b8bc-d9699219293d]     13:     <link rel="icon" href="/icon.png" type="image/png">
2024-12-03T00:53:18.360207944Z app[web.1]: [ea8e8776-571f-42bc-b8bc-d9699219293d]     14:     <link rel="icon" href="/icon.svg" type="image/svg+xml">
2024-12-03T00:53:18.360210508Z app[web.1]: [ea8e8776-571f-42bc-b8bc-d9699219293d]     15:     <link rel="apple-touch-icon" href="/icon.png">
2024-12-03T00:53:18.360212994Z app[web.1]: [ea8e8776-571f-42bc-b8bc-d9699219293d]     16:     <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
2024-12-03T00:53:18.360218314Z app[web.1]: [ea8e8776-571f-42bc-b8bc-d9699219293d]     18:   </head>
2024-12-03T00:53:18.360220523Z app[web.1]: [ea8e8776-571f-42bc-b8bc-d9699219293d]     19:
2024-12-03T00:53:18.360222652Z app[web.1]: [ea8e8776-571f-42bc-b8bc-d9699219293d]
2024-12-03T00:53:18.360224778Z app[web.1]: [ea8e8776-571f-42bc-b8bc-d9699219293d] app/views/layouts/application.html.erb:16
```

After this, I run `RAILS_ENV=production rake assets:clean assets:precompile`and I get assets in /public/assets, with fingerprinting and everything, including `tailwind-d17179cdf940704b48a731e0e15e6260a63899ffbe991215cba75b3ef1444776.css`. Additionally `apps/assets/builds/tailwind.css` is also there, but the error doesn't go away.

I appreciate any insight.
