### ISSUE TITLE
Browserslist: caniuse-lite is outdated.

### ISSUE THREAD

**Issue by mountaindog** [rails/tailwindcss-rails#287] opened 2023-10-26 15:36 UTC
This new vanilla Rails 7.1.1 install uses --css=tailwind and importmaps (`rails new . --css tailwind`). Starting the rails server with bin/dev generates a css Browerslist warning.  

Specs:
Using asdf with ruby 3.2.2, nodejs: 21.0.0 (latest), npm: 10.2.0

```
08:47:48 web.1  | => Booting Puma
08:47:48 web.1  | => Rails 7.1.1 application starting in development 
...
08:41:04 css.1  | Browserslist: caniuse-lite is outdated. Please run:
08:41:04 css.1  |   npx update-browserslist-db@latest
08:41:04 css.1  |   Why you should do it regularly: https://github.com/browserslist/update-db#readme
08:41:04 css.1  | 
08:41:04 css.1  | Rebuilding...
08:41:04 css.1  | 
08:41:04 css.1  | Done in 172ms.
```
Running the update npx command, as suggested, generates an error. 

`update-browserslist-db: Cannot find package.json. Is this the right directory to run npx update-browserslist-db in?`

Could this be safely ignored or need attention? I have not seen this before. Granted, I have mainly used esbuild and not importmaps - perhaps it's looking for node_modules dir. I am just throwing this out there. Any guidance would be appreciated.

**Comment by flavorjones** [comment] 2023-10-27 16:18
Duplicate of #283

**Closed by flavorjones** 2023-10-27 16:18 UTC

**Comment by flavorjones** [comment] 2025-04-21 17:25
Please note that this warning is quashed as of v3.3.2
