### ISSUE TITLE
Run bin/dev, but it failed to install foreman

### ISSUE THREAD

**Issue by IgnacioFan** [rails/tailwindcss-rails#337] opened 2024-03-12 20:25 UTC
## Environment:
Ruby Version: 3.0.6
Rails Version: 7.1.3.2

## Background:
My env haven't had foreman before I added `tailwindcss-rails` to my Gemfile. After integrating tailwindcss-rails in my rails app and running `rails tailwindcss:install`, I expected `bin/dev` can automatically install foreman and execute the commands in Procfile.dev. However, I saw my terminal returned `bin/dev: 16: exec: foreman: not found`. 

## Issue:
The issue happened when running `gem list foreman -i --silent`. 

## Possible fix:
I deleted the `--silent`,  and re-ran the `bin/dev`. It did successfully execute `gem install foreman`.

**Comment by flavorjones** [comment] 2024-03-17 18:26
I'm not able to reproduce this. Can you help me by providing a complete list of commands you ran, along with the complete output?

**Comment by IgnacioFan** [comment] 2024-03-17 19:49
Sure! I manually removed foreman by `gem uninstall foreman`.
I then set up a new repo to reproduce the issue following the instructions at [tailwindcss.com](https://tailwindcss.com/docs/guides/ruby-on-rails)

```bash
rails new my_tail_test
cd my_tail_test

./bin/bundle add tailwindcss-rails
./bin/rails tailwindcss:install

# reviewed if the configs are correct
cat ./config/tailwind.config.js
cat ./app/assets/stylesheets/application.tailwind.css

./bin/dev # returns './bin/dev: 16: exec: foreman: not found'
```

![image](https://github.com/rails/tailwindcss-rails/assets/7935274/2c043ce5-9d69-4e60-ae74-2f83a9e529b9)

**Comment by flavorjones** [comment] 2024-03-24 20:36
I still cannot reproduce what you're seeing. Maybe if I show you everything I'm doing you can spot what we're doing differently (why I can't reproduce). Here's what I'm doing:

```sh
#!/usr/bin/env sh

set -ex

gem install rails
gem uninstall foreman

ruby -v
rails -v

rails new tailwindcss-issue-337
cd tailwindcss-issue-337

./bin/bundle add tailwindcss-rails
./bin/rails tailwindcss:install

./bin/dev
```

<details>
<summary>Click to see the output.</summary>

```
+ gem install rails
Successfully installed rails-7.1.3.2
1 gem installed
+ gem uninstall foreman
Remove executables:
	foreman

in addition to the gem? [Yn]  Removing foreman
Successfully uninstalled foreman-0.87.2
+ ruby -v
ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]
+ rails -v
Rails 7.1.3.2
+ rails new tailwindcss-issue-337
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /home/flavorjones/tmp/tailwindcss-issue-337/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  Dockerfile
      create  .dockerignore
      create  bin/docker-entrypoint
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/new_framework_defaults_7_1.rb
      create  config/initializers/permissions_policy.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_7_1.rb
         run  bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using rake 13.1.0
Using base64 0.2.0
Using bigdecimal 3.1.7
Using concurrent-ruby 1.2.3
Using connection_pool 2.4.1
Using drb 2.2.1
Using minitest 5.22.3
Using mutex_m 0.2.0
Using builder 3.2.4
Using erubi 1.12.0
Using racc 1.7.3
Using crass 1.0.6
Using rack 3.0.10
Using nio4r 2.7.1
Using websocket-extensions 0.1.5
Using zeitwerk 2.6.13
Using timeout 0.4.1
Using marcel 1.0.4
Using mini_mime 1.1.5
Using date 3.3.4
Using public_suffix 5.0.4
Using bindex 0.8.1
Using msgpack 1.7.2
Using bundler 2.2.33
Using matrix 0.4.2
Using regexp_parser 2.9.0
Using stringio 3.1.0
Using io-console 0.7.2
Using webrick 1.8.1
Using thor 1.3.1
Using rexml 3.2.6
Using rubyzip 2.3.2
Using websocket 1.2.10
Using sqlite3 1.7.3 (x86_64-linux)
Using i18n 1.14.4
Using rack-session 2.0.0
Using tzinfo 2.0.6
Using nokogiri 1.16.3 (x86_64-linux)
Using rack-test 2.1.0
Using websocket-driver 0.7.6
Using addressable 2.8.6
Using net-protocol 0.2.2
Using bootsnap 1.18.3
Using psych 5.1.2
Using reline 0.4.3
Using rackup 2.1.0
Using sprockets 4.2.1
Using puma 6.4.2
Using selenium-webdriver 4.18.1
Using activesupport 7.1.3.2
Using loofah 2.22.0
Using xpath 3.2.0
Using net-smtp 0.4.0.1
Using rdoc 6.6.3.1
Using net-imap 0.4.10
Using net-pop 0.1.2
Using rails-dom-testing 2.2.0
Using rails-html-sanitizer 1.6.0
Using globalid 1.2.1
Using irb 1.12.0
Using mail 2.8.1
Using activemodel 7.1.3.2
Using capybara 3.40.0
Using activejob 7.1.3.2
Using debug 1.9.1
Using activerecord 7.1.3.2
Using actionview 7.1.3.2
Using actionpack 7.1.3.2
Using jbuilder 2.11.5
Using activestorage 7.1.3.2
Using actionmailer 7.1.3.2
Using railties 7.1.3.2
Using sprockets-rails 3.4.2
Using actioncable 7.1.3.2
Using actiontext 7.1.3.2
Using actionmailbox 7.1.3.2
Using importmap-rails 2.0.1
Using stimulus-rails 1.3.3
Using turbo-rails 2.0.5
Using web-console 4.2.1
Using rails 7.1.3.2
Bundle complete! 14 Gemfile dependencies, 81 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle lock --add-platform=x86_64-linux
Writing lockfile to /home/flavorjones/tmp/tailwindcss-issue-337/Gemfile.lock
         run  bundle binstubs bundler
       rails  importmap:install
       apply  /home/flavorjones/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/importmap-rails-2.0.1/lib/install/install.rb
  Add Importmap include tags in application layout
      insert    app/views/layouts/application.html.erb
  Create application.js module as entrypoint
      create    app/javascript/application.js
  Use vendor/javascript for downloaded pins
      create    vendor/javascript
      create    vendor/javascript/.keep
  Ensure JavaScript files are in the Sprocket manifest
      append    app/assets/config/manifest.js
  Configure importmap paths in config/importmap.rb
      create    config/importmap.rb
  Copying binstub
      create    bin/importmap
         run  bundle install
Using rake 13.1.0
Using base64 0.2.0
Using bigdecimal 3.1.7
Using concurrent-ruby 1.2.3
Using connection_pool 2.4.1
Using drb 2.2.1
Using i18n 1.14.4
Using minitest 5.22.3
Using mutex_m 0.2.0
Using tzinfo 2.0.6
Using activesupport 7.1.3.2
Using builder 3.2.4
Using erubi 1.12.0
Using racc 1.7.3
Using nokogiri 1.16.3 (x86_64-linux)
Using rails-dom-testing 2.2.0
Using crass 1.0.6
Using loofah 2.22.0
Using rails-html-sanitizer 1.6.0
Using actionview 7.1.3.2
Using rack 3.0.10
Using rack-session 2.0.0
Using rack-test 2.1.0
Using actionpack 7.1.3.2
Using nio4r 2.7.1
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.6
Using zeitwerk 2.6.13
Using actioncable 7.1.3.2
Using globalid 1.2.1
Using activejob 7.1.3.2
Using activemodel 7.1.3.2
Using timeout 0.4.1
Using activerecord 7.1.3.2
Using marcel 1.0.4
Using activestorage 7.1.3.2
Using mini_mime 1.1.5
Using date 3.3.4
Using net-protocol 0.2.2
Using net-imap 0.4.10
Using net-pop 0.1.2
Using net-smtp 0.4.0.1
Using mail 2.8.1
Using actionmailbox 7.1.3.2
Using actionmailer 7.1.3.2
Using actiontext 7.1.3.2
Using public_suffix 5.0.4
Using addressable 2.8.6
Using bindex 0.8.1
Using msgpack 1.7.2
Using bootsnap 1.18.3
Using bundler 2.2.33
Using matrix 0.4.2
Using regexp_parser 2.9.0
Using xpath 3.2.0
Using capybara 3.40.0
Using stringio 3.1.0
Using psych 5.1.2
Using rdoc 6.6.3.1
Using io-console 0.7.2
Using reline 0.4.3
Using irb 1.12.0
Using debug 1.9.1
Using webrick 1.8.1
Using rackup 2.1.0
Using thor 1.3.1
Using railties 7.1.3.2
Using importmap-rails 2.0.1
Using jbuilder 2.11.5
Using puma 6.4.2
Using rails 7.1.3.2
Using rexml 3.2.6
Using rubyzip 2.3.2
Using websocket 1.2.10
Using selenium-webdriver 4.18.1
Using sprockets 4.2.1
Using sprockets-rails 3.4.2
Using sqlite3 1.7.3 (x86_64-linux)
Using stimulus-rails 1.3.3
Using turbo-rails 2.0.5
Using web-console 4.2.1
Bundle complete! 14 Gemfile dependencies, 81 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
       rails  turbo:install stimulus:install
       apply  /home/flavorjones/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/turbo-rails-2.0.5/lib/install/turbo_with_importmap.rb
  Import Turbo
      append    app/javascript/application.js
  Pin Turbo
      append    config/importmap.rb
         run  bundle install
Using rake 13.1.0
Using base64 0.2.0
Using bigdecimal 3.1.7
Using concurrent-ruby 1.2.3
Using connection_pool 2.4.1
Using drb 2.2.1
Using i18n 1.14.4
Using minitest 5.22.3
Using mutex_m 0.2.0
Using tzinfo 2.0.6
Using activesupport 7.1.3.2
Using builder 3.2.4
Using erubi 1.12.0
Using racc 1.7.3
Using nokogiri 1.16.3 (x86_64-linux)
Using rails-dom-testing 2.2.0
Using crass 1.0.6
Using loofah 2.22.0
Using rails-html-sanitizer 1.6.0
Using actionview 7.1.3.2
Using rack 3.0.10
Using rack-session 2.0.0
Using rack-test 2.1.0
Using actionpack 7.1.3.2
Using nio4r 2.7.1
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.6
Using zeitwerk 2.6.13
Using actioncable 7.1.3.2
Using globalid 1.2.1
Using activejob 7.1.3.2
Using activemodel 7.1.3.2
Using timeout 0.4.1
Using activerecord 7.1.3.2
Using marcel 1.0.4
Using activestorage 7.1.3.2
Using mini_mime 1.1.5
Using date 3.3.4
Using net-protocol 0.2.2
Using net-imap 0.4.10
Using net-pop 0.1.2
Using net-smtp 0.4.0.1
Using mail 2.8.1
Using actionmailbox 7.1.3.2
Using actionmailer 7.1.3.2
Using actiontext 7.1.3.2
Using public_suffix 5.0.4
Using addressable 2.8.6
Using bindex 0.8.1
Using msgpack 1.7.2
Using bootsnap 1.18.3
Using bundler 2.2.33
Using matrix 0.4.2
Using regexp_parser 2.9.0
Using xpath 3.2.0
Using capybara 3.40.0
Using stringio 3.1.0
Using psych 5.1.2
Using rdoc 6.6.3.1
Using io-console 0.7.2
Using reline 0.4.3
Using irb 1.12.0
Using debug 1.9.1
Using webrick 1.8.1
Using rackup 2.1.0
Using thor 1.3.1
Using railties 7.1.3.2
Using importmap-rails 2.0.1
Using jbuilder 2.11.5
Using puma 6.4.2
Using rails 7.1.3.2
Using rexml 3.2.6
Using rubyzip 2.3.2
Using websocket 1.2.10
Using selenium-webdriver 4.18.1
Using sprockets 4.2.1
Using sprockets-rails 3.4.2
Using sqlite3 1.7.3 (x86_64-linux)
Using stimulus-rails 1.3.3
Using turbo-rails 2.0.5
Using web-console 4.2.1
Bundle complete! 14 Gemfile dependencies, 81 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Run turbo:install:redis to switch on Redis and use it in development for turbo streams
       apply  /home/flavorjones/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/stimulus-rails-1.3.3/lib/install/stimulus_with_importmap.rb
  Create controllers directory
      create    app/javascript/controllers
      create    app/javascript/controllers/index.js
      create    app/javascript/controllers/application.js
      create    app/javascript/controllers/hello_controller.js
  Import Stimulus controllers
      append    app/javascript/application.js
  Pin Stimulus
  Appending: pin "@hotwired/stimulus", to: "stimulus.min.js"
      append    config/importmap.rb
  Appending: pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
      append    config/importmap.rb
  Pin all controllers
  Appending: pin_all_from "app/javascript/controllers", under: "controllers"
      append    config/importmap.rb
         run  bundle install
Using rake 13.1.0
Using base64 0.2.0
Using bigdecimal 3.1.7
Using concurrent-ruby 1.2.3
Using connection_pool 2.4.1
Using drb 2.2.1
Using i18n 1.14.4
Using minitest 5.22.3
Using mutex_m 0.2.0
Using tzinfo 2.0.6
Using activesupport 7.1.3.2
Using builder 3.2.4
Using erubi 1.12.0
Using racc 1.7.3
Using nokogiri 1.16.3 (x86_64-linux)
Using rails-dom-testing 2.2.0
Using crass 1.0.6
Using loofah 2.22.0
Using rails-html-sanitizer 1.6.0
Using actionview 7.1.3.2
Using rack 3.0.10
Using rack-session 2.0.0
Using rack-test 2.1.0
Using actionpack 7.1.3.2
Using nio4r 2.7.1
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.6
Using zeitwerk 2.6.13
Using actioncable 7.1.3.2
Using globalid 1.2.1
Using activejob 7.1.3.2
Using activemodel 7.1.3.2
Using timeout 0.4.1
Using activerecord 7.1.3.2
Using marcel 1.0.4
Using activestorage 7.1.3.2
Using mini_mime 1.1.5
Using date 3.3.4
Using net-protocol 0.2.2
Using net-imap 0.4.10
Using net-pop 0.1.2
Using net-smtp 0.4.0.1
Using mail 2.8.1
Using actionmailbox 7.1.3.2
Using actionmailer 7.1.3.2
Using actiontext 7.1.3.2
Using public_suffix 5.0.4
Using addressable 2.8.6
Using bindex 0.8.1
Using msgpack 1.7.2
Using bootsnap 1.18.3
Using bundler 2.2.33
Using matrix 0.4.2
Using regexp_parser 2.9.0
Using xpath 3.2.0
Using capybara 3.40.0
Using stringio 3.1.0
Using psych 5.1.2
Using rdoc 6.6.3.1
Using io-console 0.7.2
Using reline 0.4.3
Using irb 1.12.0
Using debug 1.9.1
Using webrick 1.8.1
Using rackup 2.1.0
Using thor 1.3.1
Using railties 7.1.3.2
Using importmap-rails 2.0.1
Using jbuilder 2.11.5
Using puma 6.4.2
Using rails 7.1.3.2
Using rexml 3.2.6
Using rubyzip 2.3.2
Using websocket 1.2.10
Using selenium-webdriver 4.18.1
Using sprockets 4.2.1
Using sprockets-rails 3.4.2
Using sqlite3 1.7.3 (x86_64-linux)
Using stimulus-rails 1.3.3
Using turbo-rails 2.0.5
Using web-console 4.2.1
Bundle complete! 14 Gemfile dependencies, 81 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
+ cd tailwindcss-issue-337
+ ./bin/bundle add tailwindcss-rails
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using rake 13.1.0
Using base64 0.2.0
Using bigdecimal 3.1.7
Using concurrent-ruby 1.2.3
Using connection_pool 2.4.1
Using minitest 5.22.3
Using mutex_m 0.2.0
Using builder 3.2.4
Using racc 1.7.3
Using rack 3.0.10
Using drb 2.2.1
Using erubi 1.12.0
Using crass 1.0.6
Using nio4r 2.7.1
Using websocket-extensions 0.1.5
Using zeitwerk 2.6.13
Using mini_mime 1.1.5
Using timeout 0.4.1
Using marcel 1.0.4
Using date 3.3.4
Using public_suffix 5.0.4
Using bundler 2.2.33
Using bindex 0.8.1
Using msgpack 1.7.2
Using matrix 0.4.2
Using regexp_parser 2.9.0
Using thor 1.3.1
Using stringio 3.1.0
Using io-console 0.7.2
Using webrick 1.8.1
Using rexml 3.2.6
Using rubyzip 2.3.2
Using websocket 1.2.10
Using sqlite3 1.7.3 (x86_64-linux)
Using i18n 1.14.4
Using tzinfo 2.0.6
Using nokogiri 1.16.3 (x86_64-linux)
Using rack-session 2.0.0
Using rack-test 2.1.0
Using sprockets 4.2.1
Using websocket-driver 0.7.6
Using net-protocol 0.2.2
Using addressable 2.8.6
Using puma 6.4.2
Using bootsnap 1.18.3
Using reline 0.4.3
Using psych 5.1.2
Using rackup 2.1.0
Using loofah 2.22.0
Using xpath 3.2.0
Using selenium-webdriver 4.18.1
Using activesupport 7.1.3.2
Using net-imap 0.4.10
Using net-pop 0.1.2
Using net-smtp 0.4.0.1
Using capybara 3.40.0
Using rdoc 6.6.3.1
Using rails-dom-testing 2.2.0
Using globalid 1.2.1
Using activemodel 7.1.3.2
Using rails-html-sanitizer 1.6.0
Using mail 2.8.1
Using irb 1.12.0
Using activejob 7.1.3.2
Using activerecord 7.1.3.2
Using actionview 7.1.3.2
Using debug 1.9.1
Using actionpack 7.1.3.2
Using jbuilder 2.11.5
Using railties 7.1.3.2
Using actioncable 7.1.3.2
Using activestorage 7.1.3.2
Using actionmailer 7.1.3.2
Using sprockets-rails 3.4.2
Using importmap-rails 2.0.1
Using stimulus-rails 1.3.3
Using web-console 4.2.1
Using actionmailbox 7.1.3.2
Using tailwindcss-rails 2.3.0 (x86_64-linux)
Using turbo-rails 2.0.5
Using actiontext 7.1.3.2
Using rails 7.1.3.2
+ ./bin/rails tailwindcss:install
       apply  /home/flavorjones/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/tailwindcss-rails-2.3.0-x86_64-linux/lib/install/tailwindcss.rb
  Add Tailwindcss include tags and container element in application layout
      insert    app/views/layouts/application.html.erb
      insert    app/views/layouts/application.html.erb
      insert    app/views/layouts/application.html.erb
  Build into app/assets/builds
      create    app/assets/builds
      create    app/assets/builds/.keep
      append    app/assets/config/manifest.js
      append    .gitignore
  Add default config/tailwindcss.config.js
      create    config/tailwind.config.js
  Add default app/assets/stylesheets/application.tailwind.css
      create    app/assets/stylesheets/application.tailwind.css
  Add default Procfile.dev
      create    Procfile.dev
  Ensure foreman is installed
         run    gem install foreman from "."
Successfully installed foreman-0.87.2
1 gem installed
  Add bin/dev to start foreman
      create    bin/dev
  Compile initial Tailwind build
         run    rails tailwindcss:build from "."

Rebuilding...

Done in 256ms.
         run  bundle install
Using rake 13.1.0
Using base64 0.2.0
Using bigdecimal 3.1.7
Using concurrent-ruby 1.2.3
Using connection_pool 2.4.1
Using drb 2.2.1
Using i18n 1.14.4
Using minitest 5.22.3
Using mutex_m 0.2.0
Using tzinfo 2.0.6
Using activesupport 7.1.3.2
Using builder 3.2.4
Using erubi 1.12.0
Using racc 1.7.3
Using nokogiri 1.16.3 (x86_64-linux)
Using rails-dom-testing 2.2.0
Using crass 1.0.6
Using loofah 2.22.0
Using rails-html-sanitizer 1.6.0
Using actionview 7.1.3.2
Using rack 3.0.10
Using rack-session 2.0.0
Using rack-test 2.1.0
Using actionpack 7.1.3.2
Using nio4r 2.7.1
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.6
Using zeitwerk 2.6.13
Using actioncable 7.1.3.2
Using globalid 1.2.1
Using activejob 7.1.3.2
Using activemodel 7.1.3.2
Using timeout 0.4.1
Using activerecord 7.1.3.2
Using marcel 1.0.4
Using activestorage 7.1.3.2
Using mini_mime 1.1.5
Using date 3.3.4
Using net-protocol 0.2.2
Using net-imap 0.4.10
Using net-pop 0.1.2
Using net-smtp 0.4.0.1
Using mail 2.8.1
Using actionmailbox 7.1.3.2
Using actionmailer 7.1.3.2
Using actiontext 7.1.3.2
Using public_suffix 5.0.4
Using addressable 2.8.6
Using bindex 0.8.1
Using msgpack 1.7.2
Using bootsnap 1.18.3
Using bundler 2.2.33
Using matrix 0.4.2
Using regexp_parser 2.9.0
Using xpath 3.2.0
Using capybara 3.40.0
Using stringio 3.1.0
Using psych 5.1.2
Using rdoc 6.6.3.1
Using io-console 0.7.2
Using reline 0.4.3
Using irb 1.12.0
Using debug 1.9.1
Using webrick 1.8.1
Using rackup 2.1.0
Using thor 1.3.1
Using railties 7.1.3.2
Using importmap-rails 2.0.1
Using jbuilder 2.11.5
Using puma 6.4.2
Using rails 7.1.3.2
Using rexml 3.2.6
Using rubyzip 2.3.2
Using websocket 1.2.10
Using selenium-webdriver 4.18.1
Using sprockets 4.2.1
Using sprockets-rails 3.4.2
Using sqlite3 1.7.3 (x86_64-linux)
Using stimulus-rails 1.3.3
Using tailwindcss-rails 2.3.0 (x86_64-linux)
Using turbo-rails 2.0.5
Using web-console 4.2.1
Bundle complete! 15 Gemfile dependencies, 82 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
+ ./bin/dev
16:30:33 web.1  | started with pid 1199254
16:30:33 css.1  | started with pid 1199255
16:30:34 web.1  | => Booting Puma
16:30:34 web.1  | => Rails 7.1.3.2 application starting in development 
16:30:34 web.1  | => Run `bin/rails server --help` for more startup options
16:30:34 web.1  | Puma starting in single mode...
16:30:34 web.1  | * Puma version: 6.4.2 (ruby 3.0.6-p216) ("The Eagle of Durango")
16:30:34 web.1  | *  Min threads: 5
16:30:34 web.1  | *  Max threads: 5
16:30:34 web.1  | *  Environment: development
16:30:34 web.1  | *          PID: 1199254
16:30:34 web.1  | * Listening on http://127.0.0.1:3000
16:30:34 web.1  | * Listening on http://[::1]:3000
16:30:34 web.1  | Use Ctrl-C to stop
16:30:34 css.1  | 
16:30:34 css.1  | Rebuilding...
16:30:35 css.1  | 
16:30:35 css.1  | Done in 265ms.
```

</details>

Maybe most importantly, when I run `./bin/rails tailwindcss:install` this is part of the output:

```
Ensure foreman is installed
         run    gem install foreman from "."
Successfully installed foreman-0.87.2
```

As a safety net, `bin/dev` contains this block:

```
if ! gem list foreman -i --silent; then
  echo "Installing foreman..."
  gem install foreman
fi
```

which I don't see getting run. Can you verify if foreman is installed on your system? If so, then the issue is likely your ruby installation's handling of search paths.

**Comment by flavorjones** [comment] 2024-04-27 17:08
Closing. If you can help me reproduce what you're seeing, I'm happy to reopen.

**Closed** 2024-04-27 17:08 UTC

**Comment by kimobrian** [comment] 2024-05-08 15:52
I'm experiencing the same issue:

```sh
➜  blog git:(main) ✗ gem install foreman
Successfully installed foreman-0.88.1
Parsing documentation for foreman-0.88.1
Done installing documentation for foreman after 0 seconds
1 gem installed
➜  blog git:(main) ✗ ./bin/dev
./bin/dev: line 16: exec: foreman: not found
➜  blog git:(main) ✗ which foreman
foreman not found
➜  blog git:(main) ✗ rails --version
Rails 7.1.3.2
➜  blog git:(main) ✗ ruby --version
ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-darwin23]
➜  blog git:(main) ✗
```

**Comment by alphabetek** [comment] 2024-07-28 18:14
If anyone is facing the same issue and using rbenv, you should run `rbenv rehash` as a new executable was installed.

**Comment by ssmereka** [comment] 2025-02-02 18:28
Similar to `rbenv`, if you are using the [asdf](https://asdf-vm.com) version manager with the [ruby plugin](https://github.com/asdf-vm/asdf-ruby) you need to run `asdf reshim ruby`. This will update the shims so that asdf recognizes the new foreman executable.

**Comment by pvlbzn** [comment] 2025-05-27 21:48
In my case `foreman` was not found due to environment `$PATH`.

Do
```shell
gem env | grep "EXECUTABLE DIRECTORY"
```
In my case result is
```shell
/opt/homebrew/lib/ruby/gems/3.4.0/bin
```

Add it to your `.zshrc`, `.bashrc` or any other env file:
```shell
export PATH="/opt/homebrew/lib/ruby/gems/3.4.0/bin:$PATH"
```

Open a new terminal and verify by running `foreman`.
