### ISSUE TITLE
Browserslist: caniuse-lite is outdated. Please run: 21:49:24 css.1  |   npx update-browserslist-db@latest

### ISSUE THREAD

**Issue by beshoy23** [rails/tailwindcss-rails#294] opened 2023-11-28 19:52 UTC
when running bin/dev i get this
Browserslist: caniuse-lite is outdated. Please run:
css.1  |   npx update-browserslist-db@latest

**Comment by flavorjones** [comment] 2023-11-29 03:23
Duplicate of #283

**Closed** 2023-11-29 03:23 UTC

**Comment by flavorjones** [comment] 2025-04-21 17:24
Please note that this warning is quashed as of v3.3.2
