### ISSUE TITLE
bin/rails tailwindcss:watch not triggering rebuild

### ISSUE THREAD

**Issue by ftambara** [rails/tailwindcss-rails#217] opened 2022-10-30 19:58 UTC
### Steps to reproduce
- Install or update to tailwindcss-rails [v2.0.15](https://github.com/rails/tailwindcss-rails/releases/tag/v2.0.15) (also happens with current latest, [v2.0.16](https://github.com/rails/tailwindcss-rails/releases/tag/v2.0.16))
- run either `bin/dev` or `bin/rails server` and `bin/rails tailwindcss:watch` on separate terminals.

### Expected behavior
Tailwind CSS should rebuild stylesheet after every change in files matching any `tailwind.config.js` `module.exports.content` patterns.

### Actual behavior
Changes are ignored.

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2p20

**Comment by flavorjones** [comment] 2022-10-31 13:54
Hi, @ftambara, sorry you're experiencing problems.

I'm unable to reproduce this issue. In a fresh Rails application running tailwindcss-rails v2.0.16, when I edit `config/tailwind.config.js` a rebuild is performed, and when I edit `public/404.html` a rebuild is performed (note that `'./public/*.html'` is present in the config in `module.exports.content`).

Can you help me reproduce what you're seeing?

**Comment by flavorjones** [comment] 2022-10-31 14:03
Can you include information about your system? Are you on a Mac, Linux, Windows, etc.?

Please note there is some activity upstream about the `watch` functionality which _may_ be related?

- https://github.com/tailwindlabs/tailwindcss/issues/9667

**Comment by robgough** [comment] 2022-10-31 17:34
Just to confirm I'm seeing the same problem, using Docker on an M1 Mac. Pinning the `tailwindcss-rails` gem to `2.0.14` seems to resolve the issue. I assume it's related to the upstream activity mentioned above by @flavorjones

**Comment by ftambara** [comment] 2022-11-01 19:37
Hi @flavorjones. My system runs Debian 11.
It looks like it is indeed the issue you mentioned, since the people that commented there seem to have problems with release 3.2.0, the same that tailwindcss-rails's v2.0.15 updates to.
The cited pull request seems to be on track, so I'll stick to v2.0.14 until it arrives downstream.
Thank you for your time!

**Comment by justinperkins** [comment] 2022-11-10 21:28
FWIW, I was experiencing this issue on 2.0.18 & 2.0.19. Downgrading to 2.0.14 resolved it for me. Running on Docker on an Intel Mac. I fully tore down docker (`down -v`) and rebuilt (`up --build`) each time I changed the version.

**Comment by flavorjones** [comment] 2023-03-09 22:33
Fixed in upstream releases.

**Closed by flavorjones** 2023-03-09 22:33 UTC
